apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 10
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: { duration: 60s }
        - setWeight: 100
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/anya718/ci_cd_lab@sha256:118be1c6025df78443eab5572ab8ff39d2d5e44f5944340a80d5c16eded465a7
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
